dist: trusty
sudo: false

language: php

php:
    - 7.2
    - 7.3
    - 7.4

cache:
    directories:
        - vendor

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction --prefer-source